### PR TITLE
INFODEV-306: Fix issue #37 - broken link and add additional info

### LINKED ISSUE #37: Clarify YAML array syntax for agent.plugin checks via config file
## What do you want us to know about?  
*(Check all that apply.)*

**Report a documentation issue**
- [x] Bug (misspellings, grammatical problems, broken link, format issues)
- [x] Missing information
- [ ] Incorrect information
- [ ] Feedback or suggestions
- [ ] Other

**Product**
- [ ] Product bug 
- [ ] Product feedback

**Note:** For product-related issues, you can also submit an issue from the [Rackspace Community Forum](https://community.rackspace.com/) website. 

**Tell us more about your issue**

On the page/section https://developer.rackspace.com/docs/rackspace-monitoring/v1/tech-ref-info/server-side-agent-config-yaml/#agent-plugin-check

image

1. The blog link is not linked properly
2. While supporting a user I realized it would be helpful to clarify that YAML array/list/sequences require a comma separated list inside the square brackets. Passing a space separated list would seem intuitively correct, but results in a single argument passed to the script specified by `file`.

### PR DESCRIPTION
**Pull request by cyrichardson**
Fixes #37

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-8f44d21c20/docs/rackspace-monitoring/v1/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-1d0dc93f61/docs/rackspace-monitoring/v1/)

**Review by itzg — APPROVED** [review]
Looks great and thanks for the super-fast turnaround.

**Comment by cyrichardson** [comment]
https://staging.developer.rackspace.com/build-1d0dc93f61/docs/rackspace-monitoring/v1/tech-ref-info/server-side-agent-config-yaml/

**Comment by cyrichardson** [comment]
Thank you, @itzg ! I'll merge this now.

**Pull request merged**
