### PR TITLE
add service_endpoint

### PR DESCRIPTION
**Pull request by rphillips**

### CODE REVIEW

**Review by jjbuchan — APPROVED** [review]

**Review by jjbuchan — APPROVED** [review]
+1

(test)

**Comment by jjbuchan** [comment]
+1 (test)

**Comment by jjbuchan** [comment]
+1 (test)

**Comment by cyrichardson** [comment]
@rphillips Don't worry about the failed build. Docs tool people know about it and are working on it. Basically our staging space is full. Just check what is published and make sure it's what you are expecting.

**Comment by rphillips** [comment]
@cyrichardson where would I check what is going to be published?

**Comment by cyrichardson** [comment]
@rphillips Staging is still down and the problem is being worked. I will merge this PR so the change will be published on developer.rackspace.com.

**Comment by cyrichardson** [comment]
@rphillips Here is the link to the change. Please check it is as you want it to appear. https://developer.rackspace.com/docs/rackspace-monitoring/v1/api-reference/notification-type-operations/#pagerduty-notification-type

**Comment by rphillips** [comment]
perfect thanks

**Pull request merged**
