### PR TITLE
Updates for API Guide refactoring

### PR DESCRIPTION
**Pull request by meker12**
Details about changes in issue https://github.com/rackerlabs/docs-cloud-monitoring/issues/1

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-4afb1f0e7d/docs/rackspace-monitoring/v1/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-c6de3710c4/docs/rackspace-monitoring/v1/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-13b2dee7dc/docs/rackspace-monitoring/v1/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-1f9179f04a/docs/rackspace-monitoring/v1/).

**Comment by meker12** [comment]
Fixed issues found in QE. Merging to production.

**Pull request merged**
