### PR TITLE
Fix for Issue 81

### PR DESCRIPTION
**Pull request by cyrichardson**
Fixes Issue #81

### CODE REVIEW

**Comment by cyrichardson** [comment]
@itzg Please review this PR and see if it fixes your issue #81. Thanks for the the issue and your doc efforts!

**Comment by rackernexus** [comment]
Build 19 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-ad4645820/docs/rackspace-monitoring/v1/). valid for 14 days

**Comment by cyrichardson** [comment]
@itzg  https://developer-revs.staging.deconst.org/build-ad4645820/docs/rackspace-monitoring/v1/tech-ref-info/check-type-reference/#agent-mysql

**Review by itzg — APPROVED** [review]
Looks great

**Comment by cyrichardson** [comment]
Thanks, @itzg. Merged. Should be published on the developer site shortly.

**Pull request merged**
