### PR TITLE
Fix issue 32 - incomplete information about fstab in table

### LINKED ISSUE #32: fstab description not complete
## What do you want us to know about?  
*(Check all that apply.)*

**Report a documentation issue**
- [X] Bug (misspellings, grammatical problems, broken link, format issues)
- [ ] Missing information
- [ ] Incorrect information
- [ ] Feedback or suggestions
- [ ] Other

**Product**
- [ ] Product bug 
- [ ] Product feedback

**Note:** For product-related issues, you can also submit an issue from the [Rackspace Community Forum](https://community.rackspace.com/) website. 

**Tell us more about your issue**

*Be as specific as possible. Include excerpts from the text or a screen capture when necessary.*

The description of fstab in the table on: https://developer.rackspace.com/docs/rackspace-monitoring/v1/tech-ref-info/check-type-reference/#hostinfo-check-type-ref is incomplete. It hsould read: "Reads /etc/fstab and retrieves information about the file system configuration"

### PR DESCRIPTION
**Pull request by cyrichardson**
Fixes #32 - incomplete information about fstab in table

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-20f8550c7d/docs/rackspace-monitoring/v1/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-8b51c32e42/docs/rackspace-monitoring/v1/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-ce086498a7/docs/rackspace-monitoring/v1/)

**Comment by cyrichardson** [comment]
@joesavak Fixed and republished at https://developer.rackspace.com/docs/rackspace-monitoring/v1/tech-ref-info/check-type-reference/#hostinfo-check-type-ref

**Pull request merged**
