### PR TITLE
Fix issue 48

### PR DESCRIPTION
**Pull request by cyrichardson**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-0d7e44ba3b/docs/rackspace-monitoring/v1/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-25fe82e36f/docs/rackspace-monitoring/v1/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-4f3585d54f/docs/rackspace-monitoring/v1/)

**Comment by cyrichardson** [comment]
@itzg Please review content change at https://staging.developer.rackspace.com/build-4f3585d54f/docs/rackspace-monitoring/v1/tech-ref-info/check-type-reference/#id7

I added your suggested example below the attribute table. I didn't see any precedent for adding examples like this and this seemed like the "closest place" to add it.

See issue #48 for more info.

**Review by itzg — APPROVED** [review]
Perfect! Thanks.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-e96c04ea32/docs/rackspace-monitoring/v1/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-73937f87bf/docs/rackspace-monitoring/v1/)

**Review by itzg — APPROVED** [review]

**Pull request merged**
