### PR TITLE
Fix formatting of agent check tables

### PR DESCRIPTION
**Pull request by narcher7**
**Quality audit reminder**

Doc team: While logged in using your O365 account, complete the quality checklist at http://bit.ly/2ggvdii. Use the checklist for significant doc changes or additions submitted by you or a non-doc staff contributor.

- Fixes issue #12

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-781059ab44/docs/rackspace-monitoring/v1/). :bow:

**Comment by cyrichardson** [comment]
@DonNateR The tables here all look ok to me: https://staging.developer.rackspace.com/build-781059ab44/docs/rackspace-monitoring/v1/tech-ref-info/check-type-reference/

Are you ready for a merge?

**Review by cyrichardson — APPROVED** [review]

**Comment by narcher7** [comment]
@cyrichardson: Feel free to merge whenever you're ready!

**Comment by cyrichardson** [comment]
@DonNateR Merged!

**Pull request merged**
