### PR TITLE
Make zones lower case per issue #54

### LINKED ISSUE #54: monitoring_snet_region config docs
## What do you want us to know about?  

**Report a documentation issue**
- [ ] Bug (misspellings, grammatical problems, broken link, format issues)
- [ ] Missing information
- [x] Incorrect information
- [ ] Feedback or suggestions
- [ ] Other

Hi there!

I wanted to give feedback on the following part of the docs:

https://github.com/rackerlabs/docs-cloud-monitoring/blame/00f4d84db3f2759df754dfecfec5424bc990d25d/api-docs/getting-started/install-configure.rst#L780

```
monitoring_snet_region

string 

Optional. This option tells the agent to connect to the agent endpoints over
the Rackspace ServiceNet (instead of over the public Internet). Valid regions
are DFW, ORD, LON, SYD, HKG,  and IAD. If option is set, the value must 
match the region of the agent and the service it is running on.
```

It looks like the regions are correct, but the regions have to be specified in the config file in _lower case_. When using upper case for the region with the agent, it'll throw an error like this:

```
Sat May 12 02:57:32 PM 2018 ERR: Invalid configuration: snet_region 'DFW' is not supported.
```

Switch to lower case, and it works:

```
Sat May 12 02:58:12 PM 2018 INF: Using ServiceNet endpoints in dfw region
Sat May 12 02:58:12 PM 2018 INF: Confd -> reading files in /etc/rackspace-monitoring-agent.conf.d
Sat May 12 02:58:12 PM 2018 INF: Upgrades are enabled
Sat May 12 02:58:12 PM 2018 INF: 10.190.252.11:8443 (hostname=agent-endpoint-dfwsnet.monitoring.api.rackspacecloud.com connID=1) -> Connected
```

### PR DESCRIPTION
**Pull request by cyrichardson**
Closes #54

### CODE REVIEW

**Comment by cyrichardson** [comment]
@brint Please review and provide feedback. Thank you!

https://staging.developer.rackspace.com/build-d8d87cc9a4/docs/rackspace-monitoring/v1/getting-started/install-configure/#configure-the-agent

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-d8d87cc9a4/docs/rackspace-monitoring/v1/)

**Review by brint — APPROVED** [review]
Looks good!

**Comment by cyrichardson** [comment]
Thanks @brint. Publishing now.

**Comment by cyrichardson** [comment]
https://developer.rackspace.com/docs/rackspace-monitoring/v1/getting-started/install-configure/#configure-the-agent

**Pull request merged**
