### PR TITLE
Clarification on filesystem metrics

### PR DESCRIPTION
**Pull request by wolfdancer**
**Quality audit reminder**

Doc team: While logged in using your O365 account, complete the quality checklist at http://bit.ly/2hwvBKX. Use the checklist for significant doc changes or additions submitted by you or a non-doc staff contributor.

Fix issue #11 by adding clarification on the metrics returned by agent.filesystem check.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-7523b1c312/docs/rackspace-monitoring/v1/). :bow:

**Comment by cyrichardson** [comment]
@wolfdancer @DonNateR These changes look good to me. Leaving unmerged for Nate's review/merge.

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-a44f67c6a6/docs/rackspace-monitoring/v1/).

**Comment by cyrichardson** [comment]
@DonNateR Now have triple ticks ``` around reserved space. Should that be double ticks ``?

**Comment by narcher7** [comment]
@cyrichardson: That's my bad. Forgot how code blocks in RST work :). Fixing now.

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-d3cc45cbc5/docs/rackspace-monitoring/v1/).

**Review by narcher7 — COMMENTED** [review]
This should be ready to merge!

**Comment by cyrichardson** [comment]
LGTM - merging

**Pull request merged**
