### PR TITLE
Update to fix reported issue 39

### LINKED ISSUE #39: MaaS API / Create Suppression formatting/info
## What do you want us to know about?  
*(Check all that apply.)*

**Report a documentation issue**
- [x] Bug (misspellings, grammatical problems, broken link, format issues)
- [ ] Missing information
- [ ] Incorrect information
- [ ] Feedback or suggestions
- [ ] Other

**Product**
- [ ] Product bug 
- [ ] Product feedback

**Note:** For product-related issues, you can also submit an issue from the [Rackspace Community Forum](https://community.rackspace.com/) website. 

**Tell us more about your issue**

The information under "Create Suppression" in the MaaS API Docs (https://developer.rackspace.com/docs/rackspace-monitoring/v1/api-reference/suppressions-operations/#id14) needs a little love.

- in the response code table, the 201 result code name doesn't make sense
- the "response" section is filled with more request examples instead of information regarding response info

*Be as specific as possible. Include excerpts from the text or a screen capture when necessary.*

### PR DESCRIPTION
**Pull request by cyrichardson**
Fixes #39

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-2bd5d6d673/docs/rackspace-monitoring/v1/). :bow:

**Comment by cyrichardson** [comment]
@toxick Please take a look and feel free to provide an additional information that you would like to be included.

**Comment by aaronsegura** [comment]
I would suggest adding this to the '201' description:

    'Location' header contains a link to the newly created suppression.

**Comment by cyrichardson** [comment]
Will do, @toxick. Stay tuned.

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-9b5998be9a/docs/rackspace-monitoring/v1/).

**Comment by cyrichardson** [comment]
@toxick I applied your review comment. Thanks! Please recheck and let me know if you are ready for this to be merged.

**Comment by aaronsegura** [comment]
Looks good!  Thanks for the quick response!

**Comment by cyrichardson** [comment]
Thanks you for supporting the docs! Merging now.

**Pull request merged**
