### PR TITLE
Change check to alarm in disabled row of table

### LINKED ISSUE #61: Alarms API documentation incorrect for disabled property
## What do you want us to know about?  
*(Check all that apply.)*

**Report a documentation issue**
- [x] Bug (misspellings, grammatical problems, broken link, format issues)
- [ ] Missing information
- [ ] Incorrect information
- [ ] Feedback or suggestions
- [ ] Other

**Product**
- [ ] Product bug 
- [x] Product feedback

**Note:** For product-related issues, you can also submit an issue from the [Rackspace Community Forum](https://community.rackspace.com/) website. 

I noticed the wording for Alarms is incorrect.
https://developer.rackspace.com/docs/rackspace-monitoring/v1/api-reference/alarms-operations

The disabled property states that it "Disables the check", it in fact disables the actual alarm. The Check is disabled via the property of the same name located in [Checks API](https://developer.rackspace.com/docs/rackspace-monitoring/v1/api-reference/check-operations/)

alarmapi

Thanks.

### PR DESCRIPTION
**Pull request by cyrichardson**
Fixes #61

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-e2d08842ee/docs/rackspace-monitoring/v1/)

**Comment by cyrichardson** [comment]
@FarajiA Please review the change in the PR and provide your feedback. Thanks!

**Comment by FarajiA** [comment]
LGTM 👍

**Comment by cyrichardson** [comment]
Thanks, @FarajiA - Merging.

**Pull request merged**
