### PR TITLE
fixing broken refs

### PR DESCRIPTION
**Pull request by kruzda**
just found one of these and then grep revealed the others :)

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-412ea8339a/docs/rackspace-monitoring/v1/).

**Comment by kruzda** [comment]
I might be wrong about these as it does not work on the preview o_O

edit: looks like the only thing this does not fix is the page I originally intended to fix. all the other pages are actually fixed.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-272f2e5d0d/docs/rackspace-monitoring/v1/)

**Comment by kruzda** [comment]
okay, I figured it out yay!

**Review by cyrichardson — APPROVED** [review]
Great job, @kruzda! LGTM! Merging.

**Pull request merged**
